#!/bin/bash

NAME="minio"
DISPLAY_NAME="Minio"
REPO="minio-component"
FROM="minio/minio:%VERSION%"
TYPE="component"
VARIANT="alpine"
VERSIONS="latest"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
