#!/bin/bash

NAME="minio"
DISPLAY_NAME="Minio"
REPO="minio"
FROM="minio/minio:%VERSION%"
TYPE="component"
VARIANT="alpine"
VERSIONS="RELEASE.2017-05-05T01-14-51Z"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
